### ISSUE TITLE
Use stored postgres column to check if civil servant/organization has agreed

### ISSUE THREAD

**Issue by lukasbischof** [my-zivi/my-zivi#151]
We could use a generated column for the organization/civil_servant agreed column instead of having to deal with it in the controller 

https://www.postgresql.org/docs/12/ddl-generated-columns.html

**Comment by TheFehr** [comment]
https://github.com/rails/rails/pull/39368 rails does not seem to support it yet though.

**Comment by TheFehr** [comment]
Is not implemented with custom trigger
