### ISSUE TITLE
Wording anpassen Schwerpunkprogramm

### ISSUE THREAD

**Issue by JDevadas** [my-zivi/my-zivi#302]
<img width="259" alt="Bildschirmfoto 2021-06-23 um 07 13 05" src="https://user-images.githubusercontent.com/39792037/123039447-75fd1a00-d3f2-11eb-96f5-72c5185cda55.png">

Zwei Mal Einsatz unelegant.

Stattdessen:

Nur lange Einsätze anzeigen

oder

Nur Betriebe mit Möglichkeit für langen Einsatz anzeigen

**Comment by TheFehr** [comment]
> Nur lange Einsätze anzeigen
Ist faktisch falsch.
> Nur Betriebe mit Möglichkeit für langen Einsatz anzeigen
Ist besser, aber wir durchsuchen ja Einsätze und nicht Betriebe

**Comment by lukasbischof** [comment]
Geändert zu "Nur mögliche lange Einsätze anzeigen"
