### ISSUE TITLE
Kurzübersicht Struktur anpassen

### ISSUE THREAD

**Issue by JDevadas** [my-zivi/my-zivi#303]
<img width="453" alt="Bildschirmfoto 2021-06-23 um 07 14 49" src="https://user-images.githubusercontent.com/39792037/123039593-b52b6b00-d3f2-11eb-8cfd-c97fc72714aa.png">

Struktur von kurz¨bersicht anpassen so dass keine Wörter aneinander kleben und das ganze einen bisschen anständigeren Eindruck macht

**Comment by TheFehr** [comment]
Ja hier sind wir abhängig von den Daten des Scrapers/EZivi.
Wenn es dort schlecht formatiert ist, dann führt es auch hier bei uns zu Unschönheiten

**Comment by lukasbischof** [comment]
Ich habe mir auch schon überlegt, gar keine Kurzbeschreibung anzuzeigen und einfach eine Art hovercard einzubauen. Wäre aber etwas komplizierter gewesen, weshalb ich es nicht gemacht hab

**Comment by lukasbischof** [comment]
Design wurde angepasst für bessere Übersicht. Texte können wir leider nicht allzusehr beeinflussen
