### ISSUE TITLE
Wording anpassen Kategorie

### ISSUE THREAD

**Issue by JDevadas** [my-zivi/my-zivi#304]
<img width="278" alt="Bildschirmfoto 2021-06-23 um 07 15 39" src="https://user-images.githubusercontent.com/39792037/123039650-d2603980-d3f2-11eb-83b5-3bfd4d31323c.png">

Vorbeugung Katastorphen etc.....

kürzen auf 

Katastrophen-Hilfe & Schutz oder ähnlich

**Comment by TheFehr** [comment]
Ist auf Dev immernoch der lange Namen.

**Comment by lukasbischof** [comment]
Musst den Cache löschen (LocalStorage)
