### ISSUE TITLE
Irrelevante Search Bar entfernen

### ISSUE THREAD

**Issue by JDevadas** [my-zivi/my-zivi#305]
<img width="292" alt="Bildschirmfoto 2021-06-23 um 07 17 17" src="https://user-images.githubusercontent.com/39792037/123039787-0c314000-d3f3-11eb-8c4e-5b10a47e6884.png">

Meiner Meinung nach braucht es hier keine Search Bar für den Kanton, da bereits Option vorhanden (beliebteste Optionen ZH, BE können nach oben genommen werden).

Ist aber meine Meinung, vielleicht gibts da auch andere überlegungnen

**Comment by TheFehr** [comment]
> (beliebteste Optionen ZH, BE können nach oben genommen werden).
Wir haben nach Alphabet sortiert
