### ISSUE TITLE
Implement Expense Sheets View

### ISSUE THREAD

**Issue by lukasbischof** [my-zivi/my-zivi#88]
Since this is a shared view, it may be best to have a shared view and implement a read only behaviour for civil servants and a read/write behaviour for organization administrators

**Comment by TheFehr** [comment]
@lukasbischof isn't this complete?

**Comment by lukasbischof** [comment]
I'd say no since the labels are still off and the currency display does not work.

**Comment by TheFehr** [comment]
Is done with #164
