### ISSUE TITLE
Refactor previous code and increase coverage

### ISSUE THREAD

**Issue by lukasbischof** [my-zivi/my-zivi#9]

**Comment by lukasbischof** [comment]
This should be specified more precisely

**Comment by lukasbischof** [comment]
@TheFehr What's the status of this? Are you even working on it or should it be moved back to planned column?

**Comment by TheFehr** [comment]
This is partially done. But not actively working on it

**Comment by TheFehr** [comment]
Mostly PDF's/Calculators
